include ./../_make/help.mk
include ./gcloud.mk

### GCLOUD

# Unique Project id.
GCLOUD_PROJECT_ID=gedw99-gcloud-test
# google service account JSON file
GCLOUD_SERVICE_ACCOUNT=x.json


print:
	$(MAKE) gcloud-print


